In [46]:
import numpy as np
import math as m
arr = np.zeros((3,3,3))
arr[0][0][2] = 4
print(arr)

[[[0. 0. 4.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [47]:
arry1 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
arry1[1:5:,0:2]

array([[ 4,  5],
       [ 7,  8],
       [10, 11],
       [13, 14]])

In [48]:
# x = [1,2,3]
# y = [4,5,6]

# x += 10

# print(x)

In [49]:
npx = np.array([1,2,3])
npy = np.array([4,5,6])

npx += 10
npy *= 10

print(npx)
print(npy)

[11 12 13]
[40 50 60]


In [50]:
#Calculating Distance between two points.
first_point = np.array([7,7,7])
second_point = np.array([1,1,1])

val = ((first_point - second_point)**2).sum()

distance = m.sqrt(val)

print(distance)


10.392304845413264


In [51]:
#Finding distance between a paticular point from all the point in the graph

points = np.array([4,5,8,6,2,3])

val1 = ((points - points.mean())**2).sum()

val1 = m.sqrt(val1)

print(val1)